### ISSUE TITLE
localStorageへの保存データの設計

### ISSUE THREAD

**Issue by SatoshiHaramura** [SatoshiHaramura/stock-word#33]
localStorageへ保存するデータ(キー名/値)について設計する。
(DBは使用しない方針のため)

## 1つ目
キー名：`questionCategoryId`
値：
```
'1'
```
用途：ブラウザのリロード時に、出題する問題を問題グループのidから導出し復元するため。

## 2つ目
キー名：`setQuestions`
値：
```
['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
```
用途：ブラウザのリロード時に、復習またはランダムモードを選択された場合の出題する問題を問題の番号(id)から復元するため。

## 3つ目
キー名：`incorrectQuestions`
値：`['1', '2', '3' ...]`
用途：間違えた問題の番号(id)を配列で保存しておき、`復習`モードのときにその問題番号を使用する。

## 4つ目
キー名：`isSound`
値：
```
true | false
```
用途：ブラウザのリロード時に、音声読み上げ設定を復元するため。

**Comment by cafedomancer** [comment]
- `questionCategoryId`, `incorrectQuestions`, `isSound` はユーザー固有の設定なので、まとめて 1 つのオブジェクト (ユーザー固有の設定オブジェクト) として保存してもいいかなーと思います。
- `setQuestions` は復習の場合とランダムの場合とでキーを分けないと区別できない気がしました。
- `isSound` という名前だとちょっと分かりづらいので `playSound` とか `playsSound` とかでどうでしょうか。

**Comment by SatoshiHaramura** [comment]
@cafedomancer 
お疲れさまです。
上記の頂いたコメントについて、以下に修正を行いましたので、再度ご確認いただければと思います🙇‍♂️ 

> `questionCategoryId`, `incorrectQuestions`, `isSound` はユーザー固有の設定なので、まとめて 1 つのオブジェクト (ユーザー固有の設定オブジェクト) として保存してもいいかなーと思います。

仰る通り、1つのオブジェクトに纏めても良いかなと思いましたので、以下の`userSetting`をキー名にして、その値として、1つのオブジェクトに纏めるように修正いたしました。

> `setQuestions` は復習の場合とランダムの場合とでキーを分けないと区別できない気がしました。

こちらも仰る通り、復習の場合とランダムの場合でキーを分けるように修正いたしました。
復習の場合は`reviewQuestionIds`で、ランダムの場合は`randomQuestionIds`に修正いたしました。

> `isSound` という名前だとちょっと分かりづらいので `playSound` とか `playsSound` とかでどうでしょうか。

確かに、名前が分かりづらいと思いましたので、`playSound`に修正いたしました。

## 
キー名：`userSetting`
値：
```
{
  'questionCategoryId': 1
  'reviewQuestionIds': [1, 2, 3]
  'randomQuestionIds': [1, 11, 22, 33, 44, 55, 66, 77, 88, 99, 101]
  'playSound': false
}
```

値の型注釈
```
{
  'questionCategoryId': number
  'reviewQuestionIds': number[]
  'randomQuestionIds': number[]
  'playSound': boolean
}
```

**Comment by SatoshiHaramura** [comment]
@cafedomancer 
ご確認ありがとうございます！

**Comment by SatoshiHaramura** [comment]
`問題グループ`エンティティを`レッスン`エンティティへ変更したことに伴い( https://github.com/SatoshiHaramura/stock-word/issues/35#issuecomment-1406416288 )、`questionCategoryId`を`lessonId`へ変更しました。

## 保存データ(修正版)
キー名：`userSetting`
値：
```
{
  'lessonId': 1
  'reviewQuestionIds': [1, 2, 3]
  'randomQuestionIds': [1, 11, 22, 33, 44, 55, 66, 77, 88, 99, 101]
  'playSound': false
}
```

値の型注釈
```
{
  'lessonId': number
  'reviewQuestionIds': number[]
  'randomQuestionIds': number[]
  'playSound': boolean
}
```
